# action.yml
name: 'Podman Run Action'
description: 'Run a command in a new container'
inputs:
  image:
    description: 'Image'
    required: true
  options:
    description: 'Options'
    required: false
  run:
    description: 'Run command in container'
    required: false
  shell:
    description: 'Use a specific shell'
    required: false
    default: sh
  registry:
    description: 'Registry'
    required: false
  username:
    description: 'Username'
    required: false
  password:
    description: 'Password'
    required: false
  podman_network:
    description: 'Podman Network ID'
    default: ${{ job.container.network }}
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set environment
      run: |
        echo "INPUT_USERNAME=${{ inputs.username }}" >> "$GITHUB_ENV"
        echo "INPUT_PASSWORD=${{ inputs.password }}" >> "$GITHUB_ENV"
        echo "INPUT_IMAGE=${{ inputs.image }}" >> "$GITHUB_ENV"
        echo "INPUT_PODMAN_NETWORK=${{ inputs.podman_network }}" >> "$GITHUB_ENV"
        echo "INPUT_RUN=${{ inputs.run }}" >> "$GITHUB_ENV"
        echo "INPUT_SHELL=${{ inputs.shell }}" >> "$GITHUB_ENV"
        echo "INPUT_REGISTRY=${{ inputs.registry }}" >> "$GITHUB_ENV"
        echo "INPUT_OPTIONS=${{ inputs.options }}" >> "$GITHUB_ENV"

      shell: bash
    - run: bash ${GITHUB_ACTION_PATH}/entrypoint.sh
      shell: bash
